zstyle :plugin:fast-syntax-highlighting theme "antsy"
typeset -g FAST_THEME_NAME="antsy"
: ${FAST_HIGHLIGHT_STYLES[antsydefault]:=none}
: ${FAST_HIGHLIGHT_STYLES[antsyunknown-token]:=fg=red,bold,underline}
: ${FAST_HIGHLIGHT_STYLES[antsyreserved-word]:=fg=blue,bold}
: ${FAST_HIGHLIGHT_STYLES[antsyalias]:=fg=green,underline}
: ${FAST_HIGHLIGHT_STYLES[antsysuffix-alias]:=fg=green,underline}
: ${FAST_HIGHLIGHT_STYLES[antsybuiltin]:=fg=green,bold}
: ${FAST_HIGHLIGHT_STYLES[antsyfunction]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[antsycommand]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[antsyprecommand]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[antsycommandseparator]:=fg=blue,bold}
: ${FAST_HIGHLIGHT_STYLES[antsyhashed-command]:=fg=black,bg=white}
: ${FAST_HIGHLIGHT_STYLES[antsypath]:=fg=blue,underline,bold}
: ${FAST_HIGHLIGHT_STYLES[antsypath_pathseparator]:=none}
: ${FAST_HIGHLIGHT_STYLES[antsyglobbing]:=fg=blue,bold}
: ${FAST_HIGHLIGHT_STYLES[antsyglobbing-ext]:=fg=cyan,bold}
: ${FAST_HIGHLIGHT_STYLES[antsyhistory-expansion]:=fg=blue,bold}
: ${FAST_HIGHLIGHT_STYLES[antsysingle-hyphen-option]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[antsydouble-hyphen-option]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[antsyback-quoted-argument]:=none}
: ${FAST_HIGHLIGHT_STYLES[antsysingle-quoted-argument]:=fg=white,bold}
: ${FAST_HIGHLIGHT_STYLES[antsydouble-quoted-argument]:=fg=white,bold}
: ${FAST_HIGHLIGHT_STYLES[antsydollar-quoted-argument]:=fg=white,bold}
: ${FAST_HIGHLIGHT_STYLES[antsyback-or-dollar-double-quoted-argument]:=fg=blue,bold}
: ${FAST_HIGHLIGHT_STYLES[antsyback-dollar-quoted-argument]:=fg=blue,bold}
: ${FAST_HIGHLIGHT_STYLES[antsyassign]:=none}
: ${FAST_HIGHLIGHT_STYLES[antsyredirection]:=fg=magenta,bold}
: ${FAST_HIGHLIGHT_STYLES[antsycomment]:=fg=black,bold}
: ${FAST_HIGHLIGHT_STYLES[antsyvariable]:=fg=white}
: ${FAST_HIGHLIGHT_STYLES[antsymathvar]:=fg=white,bold}
: ${FAST_HIGHLIGHT_STYLES[antsymathnum]:=fg=yellow,bold}
: ${FAST_HIGHLIGHT_STYLES[antsymatherr]:=fg=red,bold}
: ${FAST_HIGHLIGHT_STYLES[antsyassign-array-bracket]:=fg=blue}
: ${FAST_HIGHLIGHT_STYLES[antsyfor-loop-variable]:=fg=white,bold}
: ${FAST_HIGHLIGHT_STYLES[antsyfor-loop-number]:=fg=yellow,bold}
: ${FAST_HIGHLIGHT_STYLES[antsyfor-loop-operator]:=fg=blue,bold}
: ${FAST_HIGHLIGHT_STYLES[antsyfor-loop-separator]:=fg=blue,bold}
: ${FAST_HIGHLIGHT_STYLES[antsyexec-descriptor]:=fg=yellow,bold}
: ${FAST_HIGHLIGHT_STYLES[antsyhere-string-tri]:=fg=magenta,bold}
: ${FAST_HIGHLIGHT_STYLES[antsyhere-string-text]:=bg=green}
: ${FAST_HIGHLIGHT_STYLES[antsyhere-string-var]:=fg=white,bold}
: ${FAST_HIGHLIGHT_STYLES[antsysecondary]:=}
: ${FAST_HIGHLIGHT_STYLES[antsycase-input]:=fg=white,bold}
: ${FAST_HIGHLIGHT_STYLES[antsycase-parentheses]:=fg=blue}
: ${FAST_HIGHLIGHT_STYLES[antsycase-condition]:=bg=blue}
: ${FAST_HIGHLIGHT_STYLES[antsycorrect-subtle]:=fg=white,bold}
: ${FAST_HIGHLIGHT_STYLES[antsyincorrect-subtle]:=fg=red,bold}
: ${FAST_HIGHLIGHT_STYLES[antsysubtle-separator]:=fg=blue,bold}
: ${FAST_HIGHLIGHT_STYLES[antsysubtle-bg]:=bg=green}
: ${FAST_HIGHLIGHT_STYLES[antsypath-to-dir]:=fg=blue,underline,bold}
: ${FAST_HIGHLIGHT_STYLES[antsypaired-bracket]:=fg=cyan,bold}
: ${FAST_HIGHLIGHT_STYLES[antsybracket-level-1]:=fg=blue,bold}
: ${FAST_HIGHLIGHT_STYLES[antsybracket-level-2]:=fg=blue,bold}
: ${FAST_HIGHLIGHT_STYLES[antsybracket-level-3]:=fg=blue,bold}
: ${FAST_HIGHLIGHT_STYLES[antsyglobal-alias]:=fg=green,underline,bold}
: ${FAST_HIGHLIGHT_STYLES[antsysubcommand]:=fg=white,bold}
: ${FAST_HIGHLIGHT_STYLES[antsysingle-sq-bracket]:=fg=blue,bold}
: ${FAST_HIGHLIGHT_STYLES[antsydouble-sq-bracket]:=fg=blue,bold}
: ${FAST_HIGHLIGHT_STYLES[antsydouble-paren]:=fg=blue,bold}
: ${FAST_HIGHLIGHT_STYLES[antsyoptarg-string]:=fg=white,bold}
: ${FAST_HIGHLIGHT_STYLES[antsyoptarg-number]:=fg=yellow,bold}
: ${FAST_HIGHLIGHT_STYLES[antsyrecursive-base]:=}
