#!/bin/bash

DEST="/etc/issue"

if [[ $EUID -ne 0 ]]; then
   echo "Failed. You must run as root"; exit 1
fi

if [[ ! -f $DEST ]]; then
    echo "Failed. $DEST does not exist"; exit 1
fi

echo -e '' > $DEST
echo -e '   \e[1;31m▄▄▄       ██▀███   ▄████▄   ██░ ██     ██▓     ██▓ ███▄    █  █    ██ ▒██   ██▒  ' >> $DEST
echo -e '  \e[1;31m▒████▄    ▓██ ▒ ██▒▒██▀ ▀█  ▓██░ ██▒   ▓██▒    ▓██▒ ██ ▀█   █  ██  ▓██▒▒▒ █ █ ▒░  ' >> $DEST
echo -e '  \e[1;31m▒██  ▀█▄  ▓██ ░▄█ ▒▒▓█    ▄ ▒██▀▀██░   ▒██░    ▒██▒▓██  ▀█ ██▒▓██  ▒██░░░  █   ░  ' >> $DEST
echo -e '  \e[1;31m░██▄▄▄▄██ ▒██▀▀█▄  ▒▓▓▄ ▄██▒░▓█ ░██    ▒██░    ░██░▓██▒  ▐▌██▒▓▓█  ░██░ ░ █ █ ▒   ' >> $DEST
echo -e '   \e[1;31m▓█   ▓██▒░██▓ ▒██▒▒ ▓███▀ ░░▓█▒░██▓   ░██████▒░██░▒██░   ▓██░▒▒█████▓ ▒██▒ ▒██▒  ' >> $DEST
echo -e '   \e[1;31m▒▒   ▓▒█░░ ▒▓ ░▒▓░░ ░▒ ▒  ░ ▒ ░░▒░▒   ░ ▒░▓  ░░▓  ░ ▒░   ▒ ▒ ░▒▓▒ ▒ ▒ ▒▒ ░ ░▓ ░  ' >> $DEST
echo -e '    \e[1;31m▒   ▒▒ ░  ░▒ ░ ▒░  ░  ▒    ▒ ░▒░ ░   ░ ░ ▒  ░ ▒ ░░ ░░   ░ ▒░░░▒░ ░ ░ ░░   ░▒ ░  ' >> $DEST
echo -e '    \e[1;31m░   ▒     ░░   ░ ░         ░  ░░ ░     ░ ░    ▒ ░   ░   ░ ░  ░░░ ░ ░  ░    ░    ' >> $DEST
echo -e '        \e[1;31m░  ░   ░     ░ ░       ░  ░  ░       ░  ░ ░           ░    ░      ░    ░    ' >> $DEST
echo -e '                     \e[1;31m░                                                              ' >> $DEST
echo -e '\e[0m' >> $DEST
echo -e '\e[1;37mWelcome to \e[1;32m\\n \e[1;30m(\e[1;33m\\l\e[1;30m)' >> $DEST
echo -e '\e[1;37mRunning \e[1;34mLinux \e[1;30m(\e[0;39m\\r\e[1;30m)' >> $DEST
echo -e '\e[0m' >> $DEST

echo Complete; exit 0
