#!/bin/sh

# --- session ---

# reload desktop
super + ctrl + r
	sh ~/.config/bspwm/bspwmrc

# reload keybindings
super + ctrl + c
	pkill -USR1 -x sxhkd

# quit bspwm normally
super + ctrl + q
	bspc quit

# window list
super + Tab
	rofi -show window

# desktop launcher
super + space
	rofi -show drun

# command launcher
super + grave
	rofi -show run

# launch terminal
super + Return
	urxvtc


#
# bspwm hotkeys
#

# alternate between the tiled and monocle layout
super + f
	bspc desktop -l next

# swap the current node and the biggest node
super + g
	bspc node -s biggest

# close and kill
super + {w,q}
	bspc node -{c,k}


# send the newest marked node to the newest preselected node
super + alt + g
	bspc node newest.marked.local -n newest.!automatic.local


#
# state/flags
#

# set the window state
super + {t,shift + t,s}
	bspc node -t {tiled,pseudo_tiled,floating}

# set the node flags
super + alt + {m,x,y,z}
	bspc node -g {marked,locked,sticky,private}

#
# focus/swap
#

# focus the node in the given direction
super + {_,shift + }{Up,Down,Left,Right}
	bspc node -{f,s} {north,south,west,east}

# focus the node for the given path jump
super + {a,c}
	bspc node -f @{parent,brother}

# focus the next/previous node in the current desktop
#super + {comma,period}
#	bspc node -f {next,prev}.local

# focus the next/previous desktop in the current monitor
# super + bracket{left,right}
# 	bspc desktop -f {prev,next}.local

# focus monitor left/right
super + bracket{left,right}
	bspc monitor -f {west,east}

# focus the last node/desktop
super + {_,shift + }slash
	bspc {node,desktop} -f last

# rotate desktops.
super + {_,shift} + r
  bspc node @/ -R {90,270}


# focus the older or newer node in the focus history
super + {comma,period}
	bspc wm -h off; \
	bspc node {older,newer} -f; \
	bspc wm -h on

# focus or send to the given desktop
super + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}'

#
# preselect
#

# preselect the direction
super + alt + {Up,Down,Left,Right}
	bspc node -p {north,south,west,east}

# preselect the ratio
super + alt + {1-9}
	bspc node -o 0.{1-9}

# cancel the preselection for the focused node
super + x
	bspc node -p cancel

# cancel the preselection for the focused desktop
super + alt + x
	bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

#
# move/resize
#

# expand a window by moving one of its side outward
super + shift + {h,j,k,l}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
super + shift + alt + {h,j,k,l}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# move a floating window
super + alt + {h,j,k,l}
	bspc node -v {-20 0,0 20,0 -20,20 0}
