#!/bin/sh

# Extra X settings
xsetroot -cursor_name left_ptr &

# Set random wallpaper
walsh -d /usr/share/backgrounds/antsy/nologo -t 0 &

# Custom polybar with clock and shudown\reboot menu
polybar -c /etc/X11/xdm/polybar.ini xdm-bottom &

# screenshot xdm
sleep 15 && import -w root /tmp/xdm.png &

# vim: set ft=sh:
