" vim: set ft=vim:
" ~/.vim/vimrc 2018

" for Arch Linux
runtime! archlinux.vim

" enable syntax highlighting if available
if has("syntax")
  syntax on
endif

if has("autocmd")
  filetype plugin indent on
endif

" enable pathogen
execute pathogen#infect()

" set theme
colorscheme antsy
set background=dark
set term=screen-256color

" common settings
set laststatus=2
set showmode
set number
set cursorline
set nowrap
set showcmd
set showmatch
set ignorecase
set smartcase
set incsearch
set hlsearch
set autowrite
set hidden
set wildmenu
set wildmode=longest:full,full
set scrolloff=3
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set foldmethod=indent   
set foldnestmax=10
set nofoldenable
set foldlevel=2
set encoding=utf-8
set fileencoding=utf-8
set mouse=a

" nerdtree
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'NERDTree' argv()[0] | wincmd p | ene | endif

let NERDTreeShowHidden = 1
let NERDTreeStatusline = 0
let NERDTreeWinSize = 25
let NERDTreeMinimalUI=1

" nerdtree-git
let g:NERDTreeIndicatorMapCustom = {
    \ "Modified"  : "●",
    \ "Staged"    : "▲",
    \ "Untracked" : "✱",
    \ "Renamed"   : "➤",
    \ "Unmerged"  : "♦",
    \ "Deleted"   : "✖",
    \ "Dirty"     : "✗",
    \ "Clean"     : "✔︎",
    \ 'Ignored'   : '☒',
    \ "Unknown"   : "?"
    \ }

" buftabline
let g:buftabline_show = 1
let g:buftabline_numbers = 1
let g:buftabline_indicators = "on"
let g:buftabline_separators = "on"
nnoremap <C-N> :bnext<CR>
nnoremap <C-P> :bprev<CR>

" close buffer
nnoremap cc :bp\|bd #<CR>

" save as root (only works with NOPASSWD sudo access)
cmap w!! w !sudo tee % > /dev/null
