" vim: set ft=vim:

" for Arch Linux
runtime! archlinux.vim

" enable syntax highlighting if available
if has("syntax")
  syntax on
endif

if has("autocmd")
  filetype plugin indent on
endif

" enable pathogen
execute pathogen#infect()

" set theme
colorscheme antsy
set term=screen-256color

" common settings
set laststatus=2
set shortmess+=F
set noshowmode
set noshowcmd
set nowrap
set number
set cursorline
set showmatch
set ignorecase
set smartcase
set incsearch
set hlsearch
set autowrite
set hidden
set wildmenu
set wildmode=longest:full,full
set scrolloff=3
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set foldmethod=indent   
set foldnestmax=10
set nofoldenable
set foldlevel=2
set encoding=utf-8
set fileencoding=utf-8
set mouse=a
set statusline=""

" lightline.vim
let g:lightline = { 'colorscheme': 'antsy', }

" nerdtree
" auto open NERDTree when vim starts with directory
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'NERDTree' argv()[0] | wincmd p | ene | endif
" close vim if NERDTree is only window remaining
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
" options
let NERDTreeShowHidden = 1
let NERDTreeStatusline = 2
let NERDTreeWinSize = 25
let NERDTreeMinimalUI=1
" toggle NERDTree
map <C-\> :NERDTreeToggle<CR>

" nerdtree-git
let g:NERDTreeShowGitStatus = 1
" icons to match oh-my-zsh prompt
let g:NERDTreeIndicatorMapCustom = {
    \ "Modified"  : "●",
    \ "Staged"    : "▲",
    \ "Untracked" : "✱",
    \ "Renamed"   : "➤",
    \ "Unmerged"  : "♦",
    \ "Deleted"   : "✖",
    \ "Dirty"     : "",
    \ "Clean"     : "",
    \ "Ignored"   : '',
    \ "Unknown"   : "?"
    \ }

" buftabline
let g:buftabline_show = 1
let g:buftabline_numbers = 1
let g:buftabline_indicators = "on"
let g:buftabline_separators = "off"
" map next and previous buffers
nnoremap <C-N> :bnext<CR>
nnoremap <C-P> :bprev<CR>

" vim-devicons
let g:webdevicons_conceal_nerdtree_brackets = 1

" save as root (only works with NOPASSWD sudo access)
cmap w!! w !sudo tee % > /dev/null
