" vim/vimrc

" btw
runtime! archlinux.vim

" enable syntax highlighting if available
if has("syntax")
  syntax on
endif

if has("autocmd")
  filetype plugin indent on
endif

" enable pathogen
execute pathogen#infect()

" set theme
colorscheme antsy
set term=screen-256color

" common settings
set laststatus=2
set shortmess+=F
set fillchars+=vert:│
set noshowmode
set noshowcmd
set nowrap
set number
set cursorline
set showmatch
set ignorecase
set smartcase
set incsearch
set hlsearch
set autowrite
set hidden
set wildmenu
set wildmode=longest:full,full
set scrolloff=3
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set foldmethod=indent
set foldnestmax=10
set nofoldenable
set foldlevel=2
set encoding=utf-8
set fileencoding=utf-8
set mouse=a
set statusline=""
set list lcs=tab:\┆\ 

" cwd follows current buffer
autocmd BufEnter * silent! lcd %:p:h

" save undo history
if !isdirectory($HOME."/.vim/undo")
    call mkdir($HOME."/.vim/undo", "", 0700)
endif
set undodir=~/.vim/undo
set undofile

" indentLine
let g:indentLine_enabled = 1
"let g:indentLine_setColors = 0
let g:indentLine_char = '┆'


" lightline.vim
let g:lightline = {
    \ 'colorscheme': 'antsy',
    \ 'active': {
    \   'left': [ [ 'mode', 'paste' ],
    \             [ 'readonly', 'filename', 'modified' ] ],
    \   'right': [ [ 'lineinfo' ],
    \              [ 'percent' ],
    \              [ 'fileformat', 'fileencoding', 'filetype' ],
    \              [ 'gitbranch' ],
    \              [ 'linter_checking', 'linter_errors', 'linter_warnings', 'linter_ok' ] ],
    \
    \ },
    \ 'component_function': {
    \   'gitbranch': 'fugitive#head'
    \ },
    \ }

let g:lightline.component_expand = {
    \  'linter_checking': 'lightline#ale#checking',
    \  'linter_warnings': 'lightline#ale#warnings',
    \  'linter_errors': 'lightline#ale#errors',
    \  'linter_ok': 'lightline#ale#ok',
    \ }

let g:lightline.component_type = {
    \     'linter_checking': 'left',
    \     'linter_warnings': 'warning',
    \     'linter_errors': 'error',
    \     'linter_ok': 'left',
    \ }

let g:lightline#ale#indicator_checking = " "
let g:lightline#ale#indicator_warnings = " "
let g:lightline#ale#indicator_errors = " "
let g:lightline#ale#indicator_ok = ""

" nerdtree
" auto open NERDTree when vim starts with directory
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'NERDTree' argv()[0] | wincmd p | ene | endif
" close vim if NERDTree is only window remaining
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
" options
let NERDTreeShowHidden = 1
let NERDTreeStatusline = 1
let NERDTreeWinSize = 25
let NERDTreeMinimalUI=1

" nerdtree-git
let g:NERDTreeShowGitStatus = 1

" icons to match oh-my-zsh prompt
let g:NERDTreeIndicatorMapCustom = {
    \ "Modified"  : "●",
    \ "Staged"    : "▲",
    \ "Untracked" : "✱",
    \ "Renamed"   : "➤",
    \ "Unmerged"  : "♦",
    \ "Deleted"   : "✖",
    \ "Dirty"     : "",
    \ "Clean"     : "",
    \ "Ignored"   : '',
    \ "Unknown"   : "?"
    \ }

" buftabline
let g:buftabline_show = 1
let g:buftabline_numbers = 1
let g:buftabline_indicators = "on"
let g:buftabline_separators = "off"

" Tagbar
let g:tagbar_compact = 1

" vim-devicons
let g:webdevicons_conceal_nerdtree_brackets = 1

" ALE
let b:ale_linters = ['pyflakes', 'flake8']
let g:ale_fixers = {
    \ '*': ['remove_trailing_lines', 'trim_whitespace'],
    \ 'javascript': ['eslint'],
    \ 'python': ['black', 'yapf', 'autopep8', 'isort', 'add_blank_lines_for_python_control_statements'],
    \ }
let g:ale_fix_on_save = 0

" AsyncRun auto open
let g:asyncrun_open = 10

" incsearch
map /  <Plug>(incsearch-forward)
map ?  <Plug>(incsearch-backward)
map g/ <Plug>(incsearch-stay)
let g:incsearch#auto_nohlsearch = 1
map n  <Plug>(incsearch-nohl-n)
map N  <Plug>(incsearch-nohl-N)
map *  <Plug>(incsearch-nohl-*)
map #  <Plug>(incsearch-nohl-#)
map g* <Plug>(incsearch-nohl-g*)
map g# <Plug>(incsearch-nohl-g#)

" edit vimrc and reload vimrc
nmap <silent> <leader>ve :e $MYVIMRC<CR>
nmap <silent> <leader>vr :so $MYVIMRC<CR>

" navigate panes
noremap <C-l> <C-w>l
noremap <C-h> <C-w>h
noremap <C-j> <C-w>j
noremap <C-k> <C-w>k

" toggle NERDTree
map <leader>\d :NERDTreeToggle<CR>

" save
nnoremap <leader>s :w<cr>
inoremap <leader>s <C-c>:w<cr>

" toggle paste\nopaste
set pastetoggle=<leader>z

" macros - qq record, q stop, and Q apply
nnoremap Q @q
vnoremap Q :norm @q<cr>

" ALE
nmap <leader>f <Plug>(ale_fix)
nmap <leader>] <Plug>(ale_next)
nmap <leader>[ <Plug>(ale_previous)

" toggle Tagbar
nmap <leader>\t :TagbarToggle<CR>

" map next and previous buffers
nnoremap <C-N> :bnext<CR>
nnoremap <C-P> :bprev<CR>

silent! helptags ALL

" vim: set ft=vim:
