#!/usr/bin/env bash

# use rofi to create a simple session menu

declare -A OPTIONS
OPTIONS=(
  ["Lock Desktop"]="xautolock -locknow"
  ["Reload Config"]="i3-msg reload"
  ["Reload Desktop"]="i3-msg restart"
  ["Exit Desktop"]="i3-msg exit"
)

get_options() {
    for choice in "${!OPTIONS[@]}"
    do
      echo "$choice"
    done
}

#    
main() {
  choice=$( (get_options) | rofi -dmenu -p " Session" )
  if [[ -n "$choice" ]]; then
    exec ${OPTIONS[$choice]}
  fi
}

main

exit 0


# vim: set ft=sh:
