#!/usr/bin/env bash

if ! updates_lm=$(apt-get -s -o Debug::NoLocking=true upgrade | grep -c ^Inst); then
    updates_lm=0
fi

if [ "$updates_lm" -gt 0 ]; then
    echo "$updates_lm"
else
    echo ""
fi
