#!/bin/sh

# use rofi to create a simple session menu

declare -A OPTIONS
OPTIONS=(
  ["Lock Desktop"]="xautolock -locknow"
  ["Reload Desktop"]="$HOME/.config/bspwm/bspwmrc"
  ["Reload Shortcuts"]="pkill -USR1 -x sxhkd"
  ["Exit Desktop"]="bspc quit"
)

get_options() {
    for choice in "${!OPTIONS[@]}"
    do
      echo "$choice"
    done
}

main() {
  choice=$( (get_options) | rofi -dmenu -p " Session" )
  if [[ -n "$choice" ]]; then
    exec ${OPTIONS[$choice]}
  fi
}

main

exit 0


# vim: set ft=sh :
