#!/usr/bin/env bash

declare -i ID
ID=`xinput list | grep -Eio '(touchpad|glidepoint)\s*id\=[0-9]{1,2}' | grep -Eo '[0-9]{1,2}'`

declare -i STATE
STATE=`xinput list-props $ID|grep 'Device Enabled'|awk '{print $4}'`

if [ $STATE -eq 1 ]
then
    xinput disable $ID
    # echo "Touchpad disabled."
    notify-send -u normal -t 1000 Touchpad 'Disabled' -i /usr/share/icons/oomox-antsy/devices/scalable/input-mouse.svg
else
    xinput enable $ID
    # echo "Touchpad enabled."
    notify-send -u normal -t 2500 Touchpad 'Enabled' -i /usr/share/icons/oomox-antsy/devices/scalable/input-mouse.svg
fi
