#!/bin/sh

# --- Colors ---
colors() {
  xrdb -query | grep -E "^(bspwm|\*)\.$1" | sed -r "s/^[^:]+:\s+//" | tail -n 1
}

# --- Shortcuts ---
pkill -USR1 -x sxhkd

# --- Statusbar ---
$HOME/.config/polybar/launch.sh &

# --- Monitors ---
if [ $((`xrandr --listactivemonitors | wc -l`-1)) -eq 2 ]; then
  bspc monitor VGA-1 -d 1 2
  bspc monitor DP-1 -d 3 4
else
  bspc monitor -d 1 2 3 4
fi

# --- Options ---
bspc config split_ratio               0.50
bspc config borderless_monocle        false
bspc config gapless_monocle           false
bspc config focus_follows_pointer     true
bspc config pointer_follows_monitor   true
bspc config border_width              2
bspc config window_gap                10
bspc config initial_polarity          second_child

# --- Theme ---
bspc config active_border_color       $(colors active_border_color)
bspc config focused_border_color      $(colors focused_border_color)
bspc config normal_border_color       $(colors normal_border_color)
bspc config presel_feedback_color     $(colors presel_feedback_color)

# --- Rules ---
bspc rule -a feh            state=floating focus=on follow=on manage=on
bspc rule -a mpv            state=floating focus=on follow=on manage=on
bspc rule -a Zathura        state=tiled focus=on follow=on manage=on


# vim: set ft=sh:
