#! /bin/sh

# --- Xresources ---
xres() {
  xrdb -query | grep -E "^(bspwm|\*)\.$1" | sed -r "s/^[^:]+:\s+//" | tail -n 1
}

# --- sxhkd ---
sxhkd &

# --- polybar ---
~/.config/polybar/launch.sh &

# --- monitors ---
if [ "$(bspc query -M | wc -l)" = "1" ]; then
  # default
  bspc monitor -d 1 2 3 4
else
  # dragon
  bspc monitor VGA-1 -d 1 2
  bspc monitor DP-1 -d 3 4
fi

# --- options ---
bspc config split_ratio               0.50
bspc config borderless_monocle        false
bspc config gapless_monocle           false
bspc config focus_follows_pointer     true
bspc config pointer_follows_monitor   true
bspc config border_width              1
bspc config window_gap                15
# --- borders ---
bspc config active_border_color       $(xres active_border_color)
bspc config focused_border_color      $(xres focused_border_color)
bspc config normal_border_color       $(xres normal_border_color)
bspc config presel_feedback_color     $(xres presel_feedback_color)

# --- rules ---
bspc rule -a qutebrowser    desktop='^2' focus=on follow=on
bspc rule -a Atom       desktop='^3' focus=on follow=on
bspc rule -a Thunar     desktop='^4' focus=on follow=on
bspc rule -a Gimp       desktop='^4' state=floating follow=on
