#!/usr/bin/env bash

# Import X color palette
colors() {
  xrdb -query | grep -E "^(bspwm|\*)\.$1" | sed -r "s/^[^:]+:\s+//" | tail -n 1
}

# Re\Start keybind daemon
pkill -USR1 -x sxhkd

# Re\Start status bar
$HOME/.config/polybar/launch.sh &

# Detect dual screen and setup by hostname
if [ $((`xrandr --listactivemonitors | wc -l`-1)) -eq 2 ]; then
    if [ $(hostname -s) = "python" ]; then
        bspc monitor DVI-I-1 -d 1 2 3
        bspc monitor HDMI-0 -d 4 5 6
    fi
    if [ $(hostname -s) = "dragon" ]; then
        bspc monitor VGA-1 -d 1 2 3
        bspc monitor DP-1 -d 4 5 6
    fi
else
    bspc monitor -d 1 2 3 4 5 6
fi

# Bspwm options
bspc config split_ratio               0.50
bspc config borderless_monocle        false
bspc config gapless_monocle           false
bspc config focus_follows_pointer     true
bspc config pointer_follows_monitor   true
bspc config border_width              2
bspc config window_gap                10
bspc config bottom_padding            28
bspc config initial_polarity          second_child

# Color scheme
bspc config active_border_color       $(colors active_border_color)
bspc config focused_border_color      $(colors focused_border_color)
bspc config normal_border_color       $(colors normal_border_color)
bspc config presel_feedback_color     $(colors presel_feedback_color)

# Window rules
bspc rule -a URxvt          state=pseudo_tiled
bspc rule -a qutebrowser    desktop=^4 state=tiled follow=on focus=on
bspc rule -a URxvt:RTV      desktop=^4 state=tiled follow=on focus=on
bspc rule -a feh            state=floating focus=on follow=on manage=on
bspc rule -a mpv            state=floating focus=on follow=on manage=on
bspc rule -a Zathura        state=tiled focus=on follow=on manage=on
bspc rule -a Gimp-2.8       desktop=^6 follow=on state=floating
bspc rule -a Lxappearance   desktop=^3 follow=on state=tiled
bspc rule -a Oomox          desktop=^3 follow=on state=tiled
bspc rule -a URxvt:NeoMutt  desktop=^5 follow=on state=tiled
bspc rule -a URxvt:Irssi    desktop=^5 follow=on state=tiled
bspc rule -a URxvt:LitStats desktop=^6 follow=on state=pseudo_tiled

# vim: set ft=sh:
